### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by RikCost** [neurocracy/omnipedia#43]
The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "monolog.level.notice". in Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->process() (line 49 of /var/www/html/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php).
Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->process(Object) (Line: 80)
Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object) (Line: 767)
Symfony\Component\DependencyInjection\ContainerBuilder->compile(1) (Line: 1324)
Drupal\Core\DrupalKernel->compileContainer() (Line: 934)
Drupal\Core\DrupalKernel->initializeContainer() (Line: 494)
Drupal\Core\DrupalKernel->boot() (Line: 702)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

![image](https://github.com/neurocracy/drupal-omnipedia-user/assets/69048938/f047eae9-1fce-4a86-8242-92e32d2f30ca)

![image](https://github.com/neurocracy/drupal-omnipedia-user/assets/69048938/cf362769-603c-4460-951f-c100f41291e1)

**Comment by Ambient-Impact** [comment]
I would guess it's probably due to this being included without the Monolog module being installed yet at that point:

https://github.com/neurocracy/omnipedia/blob/9f84e3b1f4782f2ef17916bf6c3dbbabcf7d26e6/web/sites/default/settings.php#L317

The file that adds is [services.monolog.yml](https://github.com/neurocracy/omnipedia/blob/9.x/web/sites/default/services.monolog.yml) which references those parameters in the error. We encountered a similar issue when running tests which is why we have it wrapped in an if statement in there but it's fairly crude and only checks for a test environment variable. You can try commenting out that block and see if it fixes it.

**Comment by Ambient-Impact** [comment]
Decided to rework the parameters so that this shouldn't be an issue any longer.

**Comment by Ambient-Impact** [comment]
Closing this as it should be fixed. Let me know if you still run into the error.
